from enum import Enum


class Character(Enum):
    @classmethod
    def has_member(cls, key) -> bool:
        """
        Quick check to see if key is within this class.
        """
        if isinstance(key, str):
            return key.upper() in cls.__members__
        elif isinstance(key, Enum):
            return key.name in cls.__members__
        else:
            return False


class Hero(Character):
    absolute_zero = "Absolute Zero"
    akash_bhuta = "Akash'Bhuta(Hero)"
    argent_adept = "The Argent Adept"
    bench_mark = "Benchmark"
    bunker = "Bunker"
    captain_cosmic = "Captain Cosmic"
    chrono_ranger = "Chrono Ranger"
    doctor_medico = "Doctor Medico(Void Guard)"
    expatriette = "Expatriette"
    fanataic = "Fanatic"
    guise = "Guise"
    haka = "Haka"
    harpy = "The Harpy"
    idealist = "Idealist(Void Guard)"
    knyfe = "K.N.Y.F.E."
    la_comodora = "La Comodora"
    legacy = "Legacy"
    lifeline = "Lifeline"
    luminary = "Luminary"
    mainstay = "Mainstay(Void Guard)"
    naturalist = "The Naturalist"
    nightmist = "NightMist"
    ominitron_x = "Omnitron-X"
    parse = "Parse"
    ra = "Ra"
    scholar = "The Scholar"
    setback = "Setback"
    sky_scraper = "Sky-Scraper"
    southwest_sentinels = "The Southwest Sentinels"
    stuntman = "Stuntman"
    tachyon = "Tachyon"
    tempest = "Tempest"
    visionary = "The Visionary"
    wraith = "The Wraith"
    writhe = "Writhe(Void Guard)"


class Villain(Character):
    aeon_master = "Aeon Master"
    akash_bhuta = "Akash'Bhuta"
    ambuscade = "Ambuscade"
    apostate = "Apostate"
    baron_blade = "Baron Blade"
    biomancer = "Biomancer"
    borr_the_unstable = "Borr the Unstable"
    bugbear = "Bugbear"
    chairman = "The Chairman"
    chokepoint = "Chokepoint"
    citizen_dawn = "Citizen Dawn"
    citizens_hammer_and_anvil = "Citizens Hammer and Anvil"
    dark_mind = "Dark Mind"
    deadline = "Deadline"
    the_dreamer = "The Dreamer"
    empyreon = "Empyreon"
    the_ennead = "The Ennead"
    ermine = "Ermine"
    faultess = "Faultless"
    fright_train = "Fright Train"
    glamour = "Glamour"
    gloomweaver = "Gloomweaver"
    grand_warlord_voss = "Grand Warlord Voss"
    greazer_clutch = "Greezer Clutch"
    infinitor = "Infinitor"
    iron_legacy = "Iron Legacy"
    kaargra = "Kaargra Warfang"
    kismet = "Kismet"
    la_capitan = "La Capitan"
    matriarch = "The Matriarch"
    miss_information = "Miss Information"
    nixious_the_chosen = "Nixious The Chosen"
    oblivaeon = "OblivAeon"
    omnitron = "Omnitron"
    the_operative = "The Operative"
    plague_rat = "Plague Rat"
    progeny = "Progeny"
    proletariat = "Proletariat"
    sanction = "Sanction"
    sergeant_steel = "Sergeant Steel"
    spite = "Spite"
    voidsoul = "Voidsoul"
    wager_master = "Wager Master"


class Environment(Character):
    the_block = "The Block"
    the_celestial_tribunal = "The Celestial Tribunal"
    champion_studios = "Champion Studios"
    court_of_blood = "The Court of Blood"
    dok_thorath_capital = "Dok'Thorath Capital"
    enclave_of_the_endlings = "Enclave of the Endlings"
    the_final_wasteland = "The Final Wasteland"
    fort_adamant = "Fort Adamant"
    freedom_tower = "Freedom Tower"
    insula_primalis = "Insula Primalis"
    madame_mittermeiers = (
        "Madame Mittermeier's Fantastic Festival of Conundrums and Curiosities"
    )
    maerynian_refuge = "Maerynian Refuge"
    magmaria = "Magmaria"
    megalopolis = "Megalopolis"
    mobile_defense_platform = "Mobile Defense Platform"
    mordengrad = "Mordengrad"
    nexus_of_the_void = "Nexus of the Void"
    omnitron_iv = "Omnitron-IV"
    pike_industrial_complex = "Pike Industrial Complex"
    realm_of_discord = "Realm of Discord"
    rook_city = "Rook City"
    ruins_of_atlantis = "Ruins of Atlantis"
    silver_gulch_1883 = "Silver Gulch: 1883"
    temple_of_zhu_long = "The Temple of Zhu Long"
    time_cataclysm = "Time Cataclysm"
    tomb_of_anubis = "The Tomb of Anubis"
    wagner_mars_base = "Wagner Mars Base"
