VILLAIN_SINGLE_NAMES = [
    "Akash'Bhuta",
    "Akash'Bhuta, Definitive",
    "Akash'Bhuta, Definitive: Critical Event! Akash'Mecha",
    "Ambuscade",
    "Ambuscade, Definitive",
    "Ambuscade, Definitive, Vainglorious: Critical Event! ",
    "Anathema",
    "Anathema: Evolved",
    "Apex, Definitive",
    "Apex, Definitive, Blood Leashed: Critical Event!",
    "Apostate",
    "Baron Blade",
    "Baron Blade, Definitive",
    "Baron Blade, Definitive, Mad Bomber: Critical Event!",
    "Baron Blade, Mad Bomber",
    "Celadroch",
    "Chokepoint",
    "Citizen Dawn",
    "Citizen Dawn, Definitive",
    "Citizen Dawn, Definitive, Sunrise: Critical Event!",
    "Deadline",
    "Dendron",
    "Dendron, Windcolor",
    "Gloomweaver",
    "Gloomweaver, Definitive",
    "Gloomweaver, Definitive, Soultaker: Critical Event!",
    "Gloomweaver, Skinwalker",
    "Grand Warlord Voss",
    "Grand Warlord Voss, Definitive",
    "Grand Warlord Voss, Definitive: Critical Event! Censor",
    "Gray",
    "Infernal Choir, The",
    "Infinitor",
    "Infinitor, Heroic",
    "Iron Legacy",
    "Kaargra Warfang",
    "Kismet",
    "Kismet, Definitive",
    "Kismet, Definitive, Empowered: : Critical Event!",
    "Kismet, The Unstable",
    "La Capitan",
    "Menagerie",
    "Miss Information",
    "Mistress of Fate",
    "Mythos",
    "OblivAeon",
    "Omnitron",
    "Omnitron, Cosmic",
    "Omnitron, Definitive",
    "Omnitron, Definitive, Cosmic: Critical Event!",
    "Oriphel",
    "Outlander",
    "Phase",
    "Plague Rat",
    "Plague Rat, Definitive",
    "Plague Rat, Definitive: Critical Event! Doctor Toxica",
    "Progeny",
    "Ram, The",
    "Ram, The: 1929",
    "Screamachine",
    "Spite",
    "Spite, Agent of Gloom",
    "Spite, Definitive",
    "Spite, Definitive, Abomination: Critical Event!",
    "Swarm Eater",
    "Swarm Eater, Hivemind",
    "Terraform, Definitive",
    "Terraform, Definitive: Critical Event! Mark III",
    "The Chairman",
    "The Dreamer",
    "The Ennead",
    "The Fey Court, Definitive",
    "The Fey Court, Definitive, War Girded Dagada & Morrigan: Critical Event!",
    "The Matriarch",
    "The Matriarch, Definitive",
    "The Matriarch, Definitive: Critical Event! MOCKtriarch",
    "The Organization, Definitive",
    "The Organization, Definitive: Critical Event! The Bear",
    "Tiamat",
    "Tiamat, Hydra",
    "Vector",
    "Wager Master",
]

VILLAIN_TEAM_NAMES = [
    "Ambuscade: Team Villain",
    "Baron Blade: Team Villain",
    "Biomancer",
    "Borr the Unstable",
    "Bugbear",
    "Citizens Hammer and Anvil",
    "Ermine",
    "Friction",
    "Fright Train",
    "Greazer Clutch",
    "La Capitan: Team Villain",
    "Miss Information: Team Villain",
    "Plague Rat: Team Villain",
    "Proletariat",
    "Sergeant Steel",
    "The Operative",
]

SCION_NAMES = [
    "Aeon Master",
    "Dark Mind",
    "Empyreon",
    "Faultless",
    "Grand Warlord Voss: Scion of OblivAeon",
    "Nixious The Chosen",
    "Progeny: Scion of OblivAeon",
    "Sanction",
    "Voidsoul",
]

HERO_NAMES = [
    "Absolute Zero",
    "Absolute Zero, Definitive",
    "Absolute Zero, Definitive, First Appearance of",
    "Absolute Zero, Freedom Five",
    "Absolute Zero, Freedom Six",
    "Absolute Zero, Termi-Nation",
    "Akash'Thriya",
    "Akash'Thriya: The Spirit of the Void",
    "Alpha, Definitive",
    "Alpha, Definitive, First Appearance of",
    "Alpha, Definitive, Reporter",
    "Alpha, Definitive: 2000",
    "Baccarat",
    "Baccarat: 1929",
    "Baccarat: Ace of Sorrows",
    "Baccarat: Ace of Swords",
    "Benchmark",
    "Benchmark: Supply And Demand",
    "Bunker",
    "Bunker, Definitive",
    "Bunker, Definitive, First Appearance of",
    "Bunker, Definitive, Stealth Suit",
    "Bunker, Freedom Five",
    "Bunker, Freedom Six",
    "Bunker, GI",
    "Bunker, Termi-Nation",
    "Captain Cosmic",
    "Captain Cosmic, Definitive",
    "Captain Cosmic, Definitive, First Appearance of",
    "Captain Cosmic, Prime Wardens",
    "Captain Cosmic, XTREME Prime Wardens",
    "Captain Cosmic: Requital",
    "Chrono Ranger",
    "Chrono Ranger, Best of Times",
    "Cricket",
    "Cricket, First Response",
    "Cricket: Renegade",
    "Cricket: Wasteland Ronin",
    "Cypher",
    "Cypher, First Response",
    "Cypher: Swarming Protocool",
    "Doc Havoc",
    "Doc Havoc, First Response",
    "Doc Havoc: 2199",
    "Doctor Medico",
    "Doctor Medico: Malpractice",
    "Drift",
    "Drift: 1929/2199",
    "Drift: Through the Breach",
    "Echelon",
    "Echelon, First Response",
    "Echelon: 2199",
    "Expatriette",
    "Expatriette, Dark Watch",
    "Expatriette, Definitive",
    "Expatriette, Definitive, Dark Watch",
    "Expatriette, Definitive, First Appearance of",
    "Expatriette, Definitive: Eclipse",
    "Fanatic",
    "Fanatic, Definitive",
    "Fanatic, Definitive, First Appearance of",
    "Fanatic, Definitive, Haunted",
    "Fanatic, Prime Wardens",
    "Fanatic, Redeemer",
    "Fanatic, XTREME Prime Wardens",
    "Gargoyle",
    "Gargoyle: 2199",
    "Gargoyle: Wasteland Ronin",
    "Guise",
    "Guise, Completionist",
    "Guise, Santa",
    "Gyrosaur",
    "Gyrosaur, Speed demon",
    "Gyrosaur: Renegade",
    "Haka",
    "Haka, Definitive",
    "Haka, Definitive, Berewolf",
    "Haka, Definitive, First Appearance of",
    "Haka, Eternal",
    "Haka, Prime Wardens",
    "Haka, XTREME Prime Wardens",
    "Idealist",
    "Idealist, Super Sentai",
    "Impact",
    "Impact: Renegade",
    "Impact: Wasteland Ronin",
    "K.N.Y.F.E.",
    "K.N.Y.F.E.: Rogue Agent",
    "La Comodora",
    "La Comodora and The Curse of the Black Spot",
    "Lady of the Wood",
    "Lady of the Wood: 2199",
    "Lady of the Wood: Ministry of Strategic Science",
    "Lady of the Wood: Season of Change",
    "Legacy",
    "Legacy, America's Cleverest",
    "Legacy, America's Greatest",
    "Legacy, America's Newest",
    "Legacy, Definitive",
    "Legacy, Definitive, First Appearance of",
    "Legacy, Freedom Five",
    "Lifeline",
    "Lifeline: Bloodmage",
    "Luminary",
    "Luminary, Heroic",
    "Magnificent Mara",
    "Magnificent Mara: 1929",
    "Magnificent Mara: Ministry of Strategic Science",
    "Mainstay",
    "Mainstay: Road Warrior",
    "Malichae",
    "Malichae: Ministry of Strategic Science",
    "Malichae: Shardmaster",
    "Mr. Fixer",
    "Mr. Fixer, Dark Watch",
    "Mr. Fixer, Definitive",
    "Mr. Fixer, Definitive, Dark Watch",
    "Mr. Fixer, Definitive, First Appearance of",
    "Mr. Fixer, Definitive: Blackfist",
    "Necro",
    "Necro: 1929",
    "Necro: Warden of chaos",
    "NightMist",
    "NightMist, Dark Watch",
    "NightMist, Definitive",
    "NightMist, Definitive, Dark Watch",
    "NightMist, Definitive, First Appearance of",
    "NightMist, Definitive, Mentor",
    "Omnitron-X",
    "Omnitron-X : Omnitron-U",
    "Parse",
    "Parse: Fugue State",
    "Quicksilver",
    "Quicksilver: Renegade",
    "Quicksilver: The Uncanny",
    "Ra",
    "Ra, Definitive",
    "Ra, Definitive, Backdraft",
    "Ra, Definitive, First Appearance of",
    "Ra: Horus of the Two Horizons",
    "Ra: Setting Sun",
    "Setback",
    "Setback, Dark Watch",
    "Setback, Definitive",
    "Setback, Definitive, Dark Watch",
    "Setback, Definitive, Fey-Cursed",
    "Setback, Definitive, First Appearance of",
    "Sky-Scraper",
    "Sky-Scraper, Extremist",
    "Starlight",
    "Starlight: Genesis",
    "Starlight: Nightlore Council",
    "Stuntman",
    "Stuntman, Action Hero",
    "Tachyon",
    "Tachyon, Definitive",
    "Tachyon, Definitive, First Appearance of",
    "Tachyon, Freedom Five",
    "Tachyon, Freedom Six",
    "Tachyon, Super Scientific",
    "Tango One",
    "Tango One: 1929",
    "Tango One: Ghost Ops",
    "Tempest",
    "Tempest, Definitive",
    "Tempest, Definitive, First Appearance of",
    "Tempest, Freedom Six",
    "Tempest, Prime Wardens",
    "Tempest, XTREME Prime Wardens",
    "The Argent Adept",
    "The Argent Adept, Definitive",
    "The Argent Adept, Definitive, First Appearance of",
    "The Argent Adept, Prime Wardens",
    "The Argent Adept, XTREME Prime Wardens",
    "The Argent Adept: Dark Conductor",
    "The Harpy",
    "The Harpy, Dark Watch",
    "The Harpy, Definitive",
    "The Harpy, Definitive, Dark Watch",
    "The Harpy, Definitive, First Appearance of",
    "The Harpy, Definitive: Blood Raven",
    "The Knight",
    "The Knight, Berserker",
    "The Knight, Fair",
    "The Knight: 1929",
    "The Knight: Wasteland Ronin",
    "The Naturalist",
    "The Naturalist, The Hunted",
    "The Scholar",
    "The Scholar of the Infinite",
    "The Southwest Sentinels",
    "The Southwest Sentinels, Adamant",
    "The Stranger",
    "The Stranger, The Rune Carved",
    "The Stranger: 1929",
    "The Stranger: Wasteland Ronin",
    "The Visionary",
    "The Visionary, Dark",
    "The Visionary: Unleashed",
    "The Wraith",
    "The Wraith, Definitive",
    "The Wraith, Definitive, Detective",
    "The Wraith, Definitive, First Appearance of",
    "The Wraith, Freedom Five",
    "The Wraith, Freedom Six",
    "The Wraith, Rook City",
    "Titan",
    "Titan: 2199",
    "Titan: Ministry of Strategic Science",
    "Unity",
    "Unity, Definitive",
    "Unity, Definitive, First Appearance of",
    "Unity, Definitive, Scavanger",
    "Unity, Freedom Six",
    "Unity, Termi-Nation",
    "Vanish",
    "Vanish, First Response",
    "Vanish: 1929",
    "Writhe",
    "Writhe, Cosmic Inventor",
]

LOCATION_NAMES = [
    "Blackwood Forest",
    "Catchwater Harbor: 1929",
    "Champion Studios",
    "Chasm of a Thousand Nights",
    "Cybersphere",
    "Diamond Manor, Definitive",
    "Dok'Thorath Capital",
    "Enclave of the Endlings",
    "F.S.C Continuance Wanderer",
    "Fort Adamant",
    "Freedom Tower",
    "Freedom Tower, Definitive",
    "Halberd Experimental Research Center",
    "Insula Primalis",
    "Insula Primalis, Definitive",
    "Madame Mittermeier's Fantastic Festival of Conundrums and Curiosities",
    "Maerynian Refuge",
    "Magmaria",
    "Magmaria, Definitive",
    "Megalopolis",
    "Megalopolis, Definitive",
    "Mobile Defense Platform",
    "Mordengrad",
    "Nexus of the Void",
    "Nightlore Citadel",
    "Northspar",
    "Omnitron-IV",
    "Pike Industrial Complex",
    "Pike Industrial Complex, Definitive",
    "Realm of Discord",
    "Realm of Discord, Definitive",
    "Rook City",
    "Rook City, Definitive",
    "Ruins of Atlantis",
    "Ruins of Atlantis, Definitive",
    "Silver Gulch: 1883",
    "St. Simeons Catacombs",
    "Superstorm Akela",
    "The Block",
    "The Celestial Tribunal",
    "The Court of Blood",
    "The Final Wasteland",
    "The Temple of Zhu Long",
    "The Temple of Zhu Long, Definitive",
    "The Tomb of Anubis",
    "Time Cataclysm",
    "Vault 5",
    "Wagner Mars Base",
    "Wagner Mars Base, Definitive",
    "Wandering Isle",
    "Windmill City",
]
