"""
Names not to push out as links (usually due to SECRETS!)
"""

IGNORE_THESE = [
    "Ambuscade, Definitive",
    "Ambuscade, Definitive, Vainglorious: Critical Event! ",
    "Apex, Definitive",
    "Apex, Definitive, Blood Leashed: Critical Event!",
    "Gloomweaver, Definitive",
    "Gloomweaver, Definitive, Soultaker: Critical Event!",
    "Kismet, Definitive",
    "Kismet, Definitive, Empowered: : Critical Event!",
    "Plague Rat, Definitive",
    "Plague Rat, Definitive: Critical Event! Doctor Toxica",
    "Spite, Definitive",
    "Spite, Definitive, Abomination: Critical Event!",
    "The Fey Court, Definitive",
    "The Fey Court, Definitive, War Girded Dagada & Morrigan: Critical Event!",
    "The Organization, Definitive",
    "The Organization, Definitive: Critical Event! The Bear",
    "Alpha, Definitive",
    "Alpha, Definitive, First Appearance of",
    "Alpha, Definitive, Reporter",
    "Alpha, Definitive: 2000",
    "Bunker, Definitive, Stealth Suit",
    "Expatriette, Definitive",
    "Expatriette, Definitive, Dark Watch",
    "Expatriette, Definitive, First Appearance of",
    "Expatriette, Definitive: Eclipse",
    "Fanatic, Definitive, Haunted",
    "Haka, Definitive, Berewolf",
    "Mr. Fixer, Definitive",
    "Mr. Fixer, Definitive, Dark Watch",
    "Mr. Fixer, Definitive, First Appearance of",
    "Mr. Fixer, Definitive: Blackfist",
    "NightMist, Definitive",
    "NightMist, Definitive, Dark Watch",
    "NightMist, Definitive, First Appearance of",
    "NightMist, Definitive, Mentor",
    "Ra, Definitive, Backdraft",
    "Setback, Definitive",
    "Setback, Definitive, Dark Watch",
    "Setback, Definitive, Fey-Cursed",
    "Setback, Definitive, First Appearance of",
    "The Harpy, Definitive",
    "The Harpy, Definitive, Dark Watch",
    "The Harpy, Definitive, First Appearance of",
    "The Harpy, Definitive: Blood Raven",
    "The Wraith, Definitive, Detective",
    "Unity, Definitive, Scavanger",
    "Diamond Manor, Definitive",
    "Pike Industrial Complex, Definitive",
    "Realm of Discord, Definitive",
    "Rook City, Definitive",
    "The Temple of Zhu Long, Definitive",
]
