from enum import Enum
from common.models.enums import EnhancedEnum


class SqlTables(EnhancedEnum):
    STATISTICS_DB_NAME = "sentinel_statistics"

    # table names
    BOX_SETS = "boxSets"
    ENVIRONMENTS = "environments"
    HEROES = "heroes"
    VILLAINS = "villains"
    USERS = "users"
    GAME_DETAILS = "gameDetails"
    HERO_TEAMS = "heroTeams"
    OPPONENTS = "opponents"
    OBLIVAEON_SETUPS = "oblivaeonSetups"
    NON_POS_HERO_TEAMS = "nonPositionalHeroTeams"
    NON_POS_OPPONENTS = "nonPositionalOpponents"


class SqlColumns(EnhancedEnum):
    ID = "id"
    ID_HASH = "id_hash"
    NON_POSITIONAL_HASH = "non_positional_hash"
    FULL_NAME = "full_name"
    BOX_SET = "box_set"
    DYNAMO_META = "dynamo_meta_query"
    TOTAL_WINS = "total_wins"
    TOTAL_GAMES = "total_games"
    NEMESIS = "nemesis"
    USERNAME = "username"
    HERO_ONE = "hero_one"
    HERO_TWO = "hero_two"
    HERO_THREE = "hero_three"
    HERO_FOUR = "hero_four"
    HERO_FIVE = "hero_five"
    VILLAIN_ONE = "villain_one"
    VILLAIN_TWO = "villain_two"
    VILLAIN_THREE = "villain_three"
    VILLAIN_FOUR = "villain_four"
    VILLAIN_FIVE = "villain_five"
    SCIONS = "scions"
    SHIELD = "shield"
    REWARDS = "rewards"
    ENTER_DATE = "entered_on"
    GAME_MODE = "game_mode"
    SELECTION_METHOD = "selection_method"
    PLATFORM = "platform"
    END_RESULT = "end_result"
    ESTIMATED_TIME = "estimated_time"
    HOUSE_RULES = "house_rules"
    NUMBER_OF_PLAYERS = "number_of_players"
    NUMBER_OF_HEROES = "number_of_heroes"
    PERCEIVED_DIFFICULTY = "perceived_difficulty"
    ROUNDS = "rounds"
    OBLIVAEON_DETAIL = "oblivaeon_details"
    HERO_TEAM = "hero_team"
    ENVIRONMENT = "environment"
    VILLAIN = "villain"
    H1_INCAP = "hero_one_incapped"
    H2_INCAP = "hero_two_incapped"
    H3_INCAP = "hero_three_incapped"
    H4_INCAP = "hero_four_incapped"
    H5_INCAP = "hero_five_incapped"
    V1_INCAP = "villain_one_incapped"
    V2_INCAP = "villain_two_incapped"
    V3_INCAP = "villain_three_incapped"
    V4_INCAP = "villain_four_incapped"
    V5_INCAP = "villain_five_incapped"
    ENTRY_IS_VALID = "entry_is_valid"
    VALID_TEAM = "valid_team"
