import json

from dataclasses import dataclass, field
from common.models.character_enums import VILLAIN_DISPLAY_MAPPING, AlternateTags, Hero, Villain, HERO_DISPLAY_MAPPING, ALTERNATE_TAG_DISPLAY_MAPPING
from common.models.enums import BoxSet
from typing import Union

@dataclass
class HeroInsert():
    full_name: Union[Hero, str]
    box_set: Union[BoxSet, str]
    alternate_name:Union[AlternateTags, str, None] = field(default=None)
    dynamo_meta_query: str = field(init=False)

    def __post_init__(self):
        self.box_set = self.box_set.value
        query = {
            "pk": f"HERO#{self.full_name.value.upper()}",
            "sk": f"META#HERO" if self.alternate_name is None else f"META#HERO#ALT#{_deal_with_definitive(self.alternate_name.value).upper()}"
        }
        self.alternate_name = ALTERNATE_TAG_DISPLAY_MAPPING.get(self.alternate_name)
        self.full_name = HERO_DISPLAY_MAPPING.get(self.full_name)
        self.nemesis = VILLAIN_DISPLAY_MAPPING.get(self.nemesis)
        self.dynamo_meta_query = json.dumps(query)
        if self.alternate_name is not None:
            self.full_name = f"{self.full_name}{self.alternate_name}"

def _deal_with_definitive(name:str):
    key = "definitive_"
    if name.startswith(key):
        return name.replace(key, "{key[-1]}#")
    else:
        return name


HEROES_TO_INSERT = [
    HeroInsert(
        Hero.absolute_zero,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.absolute_zero,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.freedom_five
    ),
    HeroInsert(
        Hero.absolute_zero,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.freedom_six
    ),
    HeroInsert(
        Hero.absolute_zero,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.termi_nation
    ),
    HeroInsert(
        Hero.absolute_zero,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.absolute_zero,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.akash_thriya,
        BoxSet.OBLIVAEON
    ),
    HeroInsert(
        Hero.akash_thriya,
        BoxSet.OBLIVAEON,
        AlternateTags.spirit_of_the_void
    ),
    HeroInsert(
        Hero.argent_adept,
        BoxSet.INFERNAL_RELICS
    ),
    HeroInsert(
        Hero.argent_adept,
        BoxSet.INFERNAL_RELICS,
        AlternateTags.prime_wardens
    ),
    HeroInsert(
        Hero.argent_adept,
        BoxSet.INFERNAL_RELICS,
        AlternateTags.dark_conductor
    ),
    HeroInsert(
        Hero.argent_adept,
        BoxSet.INFERNAL_RELICS,
        AlternateTags.xtreme_prime_wardens
    ),
    HeroInsert(
        Hero.argent_adept,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.argent_adept,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.bench_mark,
        BoxSet.BENCHMARK
    ),
    HeroInsert(
        Hero.bench_mark,
        BoxSet.BENCHMARK,
        AlternateTags.supply_and_demand
    ),
    HeroInsert(
        Hero.Bunker,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.Bunker,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.freedom_five
    ),
    HeroInsert(
        Hero.Bunker,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.freedom_six
    ),
    HeroInsert(
        Hero.Bunker,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.gi
    ),
    HeroInsert(
        Hero.Bunker,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.termi_nation
    ),
    HeroInsert(
        Hero.Bunker,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.Bunker,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.captain_cosmic,
        BoxSet.WRATH_OF_THE_COSMOS
    ),
    HeroInsert(
        Hero.captain_cosmic,
        BoxSet.WRATH_OF_THE_COSMOS,
        AlternateTags.prime_wardens
    ),
    HeroInsert(
        Hero.captain_cosmic,
        BoxSet.WRATH_OF_THE_COSMOS,
        AlternateTags.xtreme_prime_wardens
    ),
    HeroInsert(
        Hero.captain_cosmic,
        BoxSet.WRATH_OF_THE_COSMOS,
        AlternateTags.requital
    ),
    HeroInsert(
        Hero.captain_cosmic,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.captain_cosmic,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.chrono_ranger,
        BoxSet.SHATTERED_TIMELINES
    ),
    HeroInsert(
        Hero.chrono_ranger,
        BoxSet.SHATTERED_TIMELINES,
        AlternateTags.best_of_times
    ),
    HeroInsert(
        Hero.doctor_medico,
        BoxSet.VOID_GUARD
    ),
    HeroInsert(
        Hero.doctor_medico,
        BoxSet.VOID_GUARD,
        AlternateTags.malpractice
    ),
    HeroInsert(
        Hero.expatriette,
        BoxSet.ROOK_CITY
    ),
    HeroInsert(
        Hero.expatriette,
        BoxSet.ROOK_CITY,
        AlternateTags.dark_watch
    ),
    HeroInsert(
        Hero.fanatic,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.fanatic,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.redeemer
    ),
    HeroInsert(
        Hero.fanatic,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.prime_wardens
    ),
    HeroInsert(
        Hero.fanatic,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.xtreme_prime_wardens
    ),
    HeroInsert(
        Hero.fanatic,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.fanatic,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.guise,
        BoxSet.GUISE
    ),
    HeroInsert(
        Hero.guise,
        BoxSet.GUISE,
        AlternateTags.santa
    ),
    HeroInsert(
        Hero.guise,
        BoxSet.GUISE,
        AlternateTags.completionist
    ),
    HeroInsert(
        Hero.haka,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.haka,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.prime_wardens
    ),
    HeroInsert(
        Hero.haka,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.xtreme_prime_wardens
    ),
    HeroInsert(
        Hero.haka,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.eternal
    ),
    HeroInsert(
        Hero.haka,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.haka,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.harpy,
        BoxSet.OBLIVAEON
    ),
    HeroInsert(
        Hero.harpy,
        BoxSet.OBLIVAEON,
        AlternateTags.dark_watch
    ),
    HeroInsert(
        Hero.idealist,
        BoxSet.VOID_GUARD
    ),
    HeroInsert(
        Hero.idealist,
        BoxSet.VOID_GUARD,
        AlternateTags.super_sentai
    ),
    HeroInsert(
        Hero.knyfe,
        BoxSet.VENGEANCE
    ),
    HeroInsert(
        Hero.knyfe,
        BoxSet.VENGEANCE,
        AlternateTags.rogue_agent
    ),
    HeroInsert(
        Hero.la_comodora,
        BoxSet.OBLIVAEON
    ),
    HeroInsert(
        Hero.la_comodora,
        BoxSet.OBLIVAEON,
        AlternateTags.curse_of_the_black_spot
    ),
    HeroInsert(
        Hero.legacy,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.legacy,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.americas_greatest
    ),
    HeroInsert(
        Hero.legacy,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.americas_newest
    ),
    HeroInsert(
        Hero.legacy,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.americas_cleverest
    ),
    HeroInsert(
        Hero.legacy,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.legacy,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.lifeline,
        BoxSet.OBLIVAEON
    ),
    HeroInsert(
        Hero.lifeline,
        BoxSet.OBLIVAEON,
        AlternateTags.bloodmage
    ),
    HeroInsert(
        Hero.luminary,
        BoxSet.OBLIVAEON
    ),
    HeroInsert(
        Hero.luminary,
        BoxSet.OBLIVAEON,
        AlternateTags.heroic
    ),
    HeroInsert(
        Hero.mainstay,
        BoxSet.VOID_GUARD
    ),
    HeroInsert(
        Hero.mainstay,
        BoxSet.VOID_GUARD,
        AlternateTags.road_warrior
    ),
    HeroInsert(
        Hero.mr_fixer,
        BoxSet.ROOK_CITY
    ),
    HeroInsert(
        Hero.mr_fixer,
        BoxSet.ROOK_CITY,
        AlternateTags.dark_watch
    ),
    HeroInsert(
        Hero.naturalist,
        BoxSet.VENGEANCE
    ),
    HeroInsert(
        Hero.naturalist,
        BoxSet.VENGEANCE,
        AlternateTags.the_hunted
    ),
    HeroInsert(
        Hero.nightmist,
        BoxSet.INFERNAL_RELICS
    ),
    HeroInsert(
        Hero.nightmist,
        BoxSet.INFERNAL_RELICS,
        AlternateTags.dark_watch
    ),
    HeroInsert(
        Hero.ominitron_x,
        BoxSet.SHATTERED_TIMELINES
    ),
    HeroInsert(
        Hero.ominitron_x,
        BoxSet.SHATTERED_TIMELINES,
        AlternateTags.u
    ),
    HeroInsert(
        Hero.parse,
        BoxSet.VENGEANCE,
    ),
    HeroInsert(
        Hero.parse,
        BoxSet.VENGEANCE,
        AlternateTags.fugue_state
    ),
    HeroInsert(
        Hero.ra,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.ra,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.horus_of_the_two_horizon
    ),
    HeroInsert(
        Hero.ra,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.setting_sun
    ),
    HeroInsert(
        Hero.ra,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.ra,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.scholar,
        BoxSet.SCHOLAR
    ),
    HeroInsert(
        Hero.scholar,
        BoxSet.SCHOLAR,
        AlternateTags.of_the_infinite
    ),
    HeroInsert(
        Hero.setback,
        BoxSet.VENGEANCE
    ),
    HeroInsert(
        Hero.setback,
        BoxSet.VENGEANCE,
        AlternateTags.dark_watch
    ),
    HeroInsert(
        Hero.sky_scraper,
        BoxSet.WRATH_OF_THE_COSMOS,
    ),
    HeroInsert(
        Hero.sky_scraper,
        BoxSet.WRATH_OF_THE_COSMOS,
        AlternateTags.extremist
    ),
    HeroInsert(
        Hero.southwest_sentinels,
        BoxSet.VENGEANCE
    ),
    HeroInsert(
        Hero.southwest_sentinels,
        BoxSet.VENGEANCE,
        AlternateTags.adamant
    ),
    HeroInsert(
        Hero.stuntman,
        BoxSet.STUNTMAN
    ),
    HeroInsert(
        Hero.stuntman,
        BoxSet.STUNTMAN,
        AlternateTags.action_hero
    ),
    HeroInsert(
        Hero.tachyon,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.tachyon,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.super_scientific
    ),
    HeroInsert(
        Hero.tachyon,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.freedom_five
    ),
    HeroInsert(
        Hero.tachyon,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.freedom_six
    ),
    HeroInsert(
        Hero.tachyon,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.tachyon,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.tempest,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.tempest,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.prime_wardens
    ),
    HeroInsert(
        Hero.tempest,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.freedom_six
    ),
    HeroInsert(
        Hero.tempest,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.xtreme_prime_wardens
    ),
    HeroInsert(
        Hero.tempest,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.tempest,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.unity,
        BoxSet.UNITY
    ),
    HeroInsert(
        Hero.unity,
        BoxSet.UNITY,
        AlternateTags.termi_nation
    ),
    HeroInsert(
        Hero.unity,
        BoxSet.UNITY,
        AlternateTags.freedom_six
    ),
    HeroInsert(
        Hero.unity,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.unity,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.visionary,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.visionary,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.dark
    ),
    HeroInsert(
        Hero.visionary,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.unleashed
    ),
    HeroInsert(
        Hero.wraith,
        BoxSet.ENHANCED_EDITION
    ),
    HeroInsert(
        Hero.wraith,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.rook_city
    ),
    HeroInsert(
        Hero.wraith,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.freedom_five
    ),
    HeroInsert(
        Hero.wraith,
        BoxSet.ENHANCED_EDITION,
        AlternateTags.freedom_six
    ),
    HeroInsert(
        Hero.wraith,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.definitive
    ),
    HeroInsert(
        Hero.wraith,
        BoxSet.DEFINITIVE_EDITION,
        AlternateTags.first_appearance
    ),
    HeroInsert(
        Hero.writhe,
        BoxSet.VOID_GUARD
    ),
    HeroInsert(
        Hero.writje,
        BoxSet.VOID_GUARD,
        AlternateTags.cosmic_inventor
    )
    
]